BEGIN TRANSACTION;
CREATE TABLE "Orchard_Framework_ContentItemRecord" ("Id"  integer primary key autoincrement, "Data" TEXT, "ContentType_id" INT );
INSERT INTO Orchard_Framework_ContentItemRecord VALUES(1,NULL,1);
INSERT INTO Orchard_Framework_ContentItemRecord VALUES(2,NULL,2);
CREATE TABLE "Orchard_Framework_ContentItemVersionRecord" ("Id"  integer primary key autoincrement, "VersionNumber" INT, "Published" BOOL, "Latest" BOOL, "Data" TEXT, "ContentItemRecord_id" INT not null );
INSERT INTO Orchard_Framework_ContentItemVersionRecord VALUES(1,1,1,1,NULL,1);
INSERT INTO Orchard_Framework_ContentItemVersionRecord VALUES(2,1,1,1,NULL,2);
CREATE TABLE "Orchard_Framework_ContentTypeRecord" ("Id"  integer primary key autoincrement, "Name" TEXT );
INSERT INTO Orchard_Framework_ContentTypeRecord VALUES(1,'Site');
INSERT INTO Orchard_Framework_ContentTypeRecord VALUES(2,'User');
CREATE TABLE "Orchard_Framework_CultureRecord" ("Id"  integer primary key autoincrement, "Culture" TEXT );
INSERT INTO Orchard_Framework_CultureRecord VALUES(1,'en-US');
CREATE TABLE "Orchard_Framework_DataMigrationRecord" ("Id"  integer primary key autoincrement, "DataMigrationClass" TEXT, "Version" INT );
INSERT INTO Orchard_Framework_DataMigrationRecord VALUES(1,'Orchard.Core.Settings.Migrations',4);
INSERT INTO Orchard_Framework_DataMigrationRecord VALUES(2,'Orchard.ContentManagement.DataMigrations.FrameworkDataMigration',2);
INSERT INTO Orchard_Framework_DataMigrationRecord VALUES(10,'Orchard.Themes.ThemesDataMigration',1);
CREATE TABLE "Orchard_Themes_ThemeSiteSettingsPartRecord" ("Id" INT not null, "CurrentThemeName" TEXT );
INSERT INTO Orchard_Themes_ThemeSiteSettingsPartRecord VALUES(1,'TheThemeMachine');
CREATE TABLE "Settings_ContentFieldRecord" ("Id"  integer primary key autoincrement, "Name" TEXT );
CREATE TABLE "Settings_ContentPartDefinitionRecord" ("Id"  integer primary key autoincrement, "Name" TEXT, "Hidden" BOOL, "Settings" TEXT );
CREATE TABLE "Settings_ContentPartFieldDefinitionRecord" ("Id"  integer primary key autoincrement, "Name" TEXT, "Settings" TEXT, "ContentFieldRecord_id" INT, "ContentPartDefinitionRecord_Id" INT );
CREATE TABLE "Settings_ContentTypeDefinitionRecord" ("Id"  integer primary key autoincrement, "Name" TEXT, "DisplayName" TEXT, "Hidden" BOOL, "Settings" TEXT );
INSERT INTO Settings_ContentTypeDefinitionRecord VALUES(1,'Site','Site',0,'<settings />');
INSERT INTO Settings_ContentTypeDefinitionRecord VALUES(10,'User','User',0,'<settings ContentTypeSettings.Creatable="False" />');
CREATE TABLE "Settings_ContentTypePartDefinitionRecord" ("Id"  integer primary key autoincrement, "Settings" TEXT, "ContentPartDefinitionRecord_id" INT, "ContentTypeDefinitionRecord_Id" INT );
CREATE TABLE "Settings_ShellDescriptorRecord" ("Id"  integer primary key autoincrement, "SerialNumber" INT );
INSERT INTO Settings_ShellDescriptorRecord VALUES(1,2);
CREATE TABLE "Settings_ShellFeatureRecord" ("Id"  integer primary key autoincrement, "Name" TEXT, "ShellDescriptorRecord_id" INT );
INSERT INTO Settings_ShellFeatureRecord VALUES(23,'Orchard.Framework',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(32,'Settings',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(33,'Shapes',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(37,'Orchard.Themes',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(40,'Orchard.Modules',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(48,'Orchard.jQuery',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(49,'Orchard.PublishLater',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(50,'Orchard.jQuery',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(91,'TheThemeMachine',1);
INSERT INTO Settings_ShellFeatureRecord VALUES(92,'Orchard.Home',1);
CREATE TABLE "Settings_ShellFeatureStateRecord" ("Id"  integer primary key autoincrement, "Name" TEXT, "InstallState" TEXT, "EnableState" TEXT, "ShellStateRecord_Id" INT );
INSERT INTO Settings_ShellFeatureStateRecord VALUES(1,'Orchard.Framework','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(10,'Settings','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(11,'Shapes','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(15,'Orchard.Themes','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(18,'Orchard.Modules','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(26,'Orchard.jQuery','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(44,'TheThemeMachine','Up','Up',1);
INSERT INTO Settings_ShellFeatureStateRecord VALUES(45,'Orchard.Home','Up','Up',1);
CREATE TABLE "Settings_ShellParameterRecord" ("Id"  integer primary key autoincrement, "Component" TEXT, "Name" TEXT, "Value" TEXT, "ShellDescriptorRecord_id" INT );
CREATE TABLE "Settings_ShellStateRecord" ("Id"  integer primary key autoincrement, "Unused" TEXT );
INSERT INTO Settings_ShellStateRecord VALUES(1,NULL);
CREATE TABLE "Settings_SiteSettings2PartRecord" ("Id" INT not null, "BaseUrl" TEXT );
INSERT INTO Settings_SiteSettings2PartRecord VALUES(1,'http://localhost:30321/OrchardLocal');
CREATE TABLE "Settings_SiteSettingsPartRecord" ("Id" INT not null, "SiteSalt" TEXT, "SiteName" TEXT, "SuperUser" TEXT, "PageTitleSeparator" TEXT, "HomePage" TEXT, "SiteCulture" TEXT, "ResourceDebugMode" TEXT default 'FromAppSetting' , "PageSize" INT, "SiteTimeZone" TEXT );
INSERT INTO Settings_SiteSettingsPartRecord VALUES(1,'c8147e8dab1c4130b33bd24b803163f6','Orchard','admin',' - ',NULL,'en-US','FromAppSetting',10,'China Standard Time');
CREATE TABLE sqlite_sequence(name,seq);
INSERT INTO sqlite_sequence VALUES('Settings_ContentTypeDefinitionRecord',29);
INSERT INTO sqlite_sequence VALUES('Orchard_Framework_DataMigrationRecord',26);
INSERT INTO sqlite_sequence VALUES('Settings_ContentPartDefinitionRecord',39);
INSERT INTO sqlite_sequence VALUES('Settings_ContentTypePartDefinitionRecord',114);
INSERT INTO sqlite_sequence VALUES('Settings_ShellDescriptorRecord',1);
INSERT INTO sqlite_sequence VALUES('Settings_ShellFeatureRecord',92);
INSERT INTO sqlite_sequence VALUES('Settings_ShellStateRecord',1);
INSERT INTO sqlite_sequence VALUES('Settings_ShellFeatureStateRecord',45);
INSERT INTO sqlite_sequence VALUES('Orchard_Framework_ContentItemRecord',14);
INSERT INTO sqlite_sequence VALUES('Orchard_Framework_ContentItemVersionRecord',14);
INSERT INTO sqlite_sequence VALUES('Orchard_Framework_ContentTypeRecord',8);
INSERT INTO sqlite_sequence VALUES('Orchard_Framework_CultureRecord',1);
COMMIT;
